name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [ opened, synchronize, reopened, closed ]
    branches: [ "main" ]

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      # (kept because your existing template used it)
      - name: Install OIDC Client from Core Package
        run: npm install @actions/core@1.6.0 @actions/http-client

      - name: Get Id Token
        uses: actions/github-script@v6
        id: idtoken
        with:
          script: |
            const coredemo = require('@actions/core')
            return await coredemo.getIDToken()
          result-encoding: string

      # --------- Build Flutter Web ----------
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'   # or pin to your exact version

      - name: Flutter pub get
        run: flutter pub get
        working-directory: .

      - name: Flutter build web
        run: flutter build web --release
        working-directory: .

      # (optional) quick sanity check so you can see index.html exists
      - name: Debug listing
        run: |
          ls -la
          ls -la build
          ls -la build/web
        working-directory: .

      # --------- Deploy to Azure SWA (upload prebuilt site) ----------
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_MUD_0BDD85A1E }}
          action: upload
          # we already built; skip Oryx build
          skip_app_build: true
          skip_api_build: true
          # path to your source (root of repo)
          app_location: .
          # path to built site (Flutter output)
          app_artifact_location: build/web
          github_id_token: ${{ steps.idtoken.outputs.result }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: close
